### ISSUE TITLE
Adopt an explicit license

### ISSUE THREAD

**Issue by keawade** [Noobulater/gmforge-core#1]
You may want to [adopt an explicit license](https://help.github.com/articles/adding-a-license-to-a-repository/#including-an-open-source-license-in-your-repository) so usage rights and your intentions are clear.

The [GitHub terms of service](https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users) state that all public code is licensed similarly to MIT/BSD licensed projects by default but can be somewhat restricted or at least clarified by adopting an explicit license.

> By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

**Comment by Noobulater** [comment]
Appreciate it, I'm deciding on a license right now. Thanks!
